files:
  includes:
    # Getting Started
    - getting-started/**/*.txt
    - new-to-pvm/**/*.txt
    - new-to-bossing/**/*.txt

    # Invention & Perks
    - invention-and-perks/**/*.txt

    # Guides
    - basic-guides/**/*.{txt,md}
    - rs3-full-boss-guides/**/*.{txt,md}
    - afk/**/*.{txt,md}
    - combat-achievements/**/*.{txt,md}
    - slayer/**/*.{txt,md}
    - one-tick-guides/**/*.{txt,md}

    # Strategy
    - dpm-advice/**/*.{txt,md}
    - upgrading-info/**/*.{txt,md}

    # Miscellaneous
    - get-involved/**/*.{txt,md}
    - editor-resources/**/*.{txt,md}
    - miscellaneous-information/**/*.{txt,md}

  excludes:
    - navigation/**/*.txt
    - archive/**/*.txt
    - commands/**/*.txt
    - osrs-commands/**/*.txt
    - osrs-guides/**/*.txt
    - miscellaneous-information/command-info.txt
    - get-involved/applications.txt
    - get-involved/editor-entry.txt
    - .github/**/*

name_convert:
  category:
    getting-started:
      alias: Getting Started
    new-to-pvm:
      alias: New to PvM
    new-to-bossing:
      alias: New to Bossing
    invention-and-perks:
      alias: Invention & Perks
    basic-guides:
      alias: Basic Guides
    rs3-full-boss-guides:
      alias: RS3 Full Boss Guides
    afk:
      alias: AFK Methods
    combat-achievements:
      alias: Combat Achievements
    slayer:
      alias: Slayer Guides
    one-tick-guides:
      alias: One Tick Guides
    dpm-advice:
      alias: Strategy
    upgrading-info:
      alias: Strategy
    get-involved:
      alias: PVME Mastery Roles
    editor-resources:
      alias: Editor Resources
    miscellaneous-information:
      alias: Miscellaneous