files:
  includes:
    - getting-started/quick-start.txt
    - getting-started/how-to-use-pvme.txt
    - getting-started/interface-guide.txt
    - getting-started/early-moneymaking-ideas.txt
    - getting-started/noncombat-skilling-guides.txt

    - new-to-pvm/**/*.txt

    - new-to-bossing/**/*.txt

    - invention-and-perks/**/*.txt
    
    - miscellaneous-information/**/*.txt

    - upgrading-info/upgrade-order/*.txt
    - upgrading-info/**/*.txt

    - dpm-advice/**/*.txt
    
    - afk/afk-overview.txt
    - afk/**/*.txt
    
    - basic-guides/**/*.txt
    
    - rs3-full-boss-guides/**/*.txt

    - slayer/overview-of-slayer.txt
    - slayer/block-prefer-list.txt
    - slayer/ultimate-slayer.txt
    - slayer/miscellaneous-slayer.txt
    - slayer/**/*.txt

    - get-involved/mastery-requirements.txt
    - get-involved/feats-requirements.txt

    - editor-resources/intro-to-editing.txt
    - editor-resources/intro-to-editing-continued.txt
    - editor-resources/editor-tools/*.txt
    - editor-resources/editor-references/*.txt
    - editor-resources/github-tutorials/*.txt

  excludes:
    - navigation/**/*.txt
    - archive/**/*.txt
    - commands/**/*.txt
    - osrs-commands/**/*.txt
    - osrs-guides/**/*.txt
    - miscellaneous-information/command-info.txt
    - get-involved/applications.txt
    - get-involved/editor-entry.txt
    - .github/**/*

#  uncategorized:
#    - '**/*.txt'

name_convert:
  category:
    invention-and-perks:
      alias: perks
      emoji: "689509250946695292"
    miscellaneous-information:
      alias: miscellaneous
    upgrading-info:
      alias: upgrades
    slayer:
      emoji: "797896049548066857"
    rs3-full-boss-guides:
      alias: full boss guides
    get-involved:
      alias: mastery
    editor-resources:
      alias: editor info

  extra_channel:
    AFK Commander Zilyana Hard Mode: afk commander zilyana hm
    AFK General Graardor Hard Mode: afk general graardor hm
    AFK Kree-arra Hard Mode: afk kree'arra hm
    AFK K'ril Tsutsaroth Hard Mode: afk k'ril tsutsaroth hm

  word:
    osrs: OSRS
    gwd1: GWD1
    gwd2: GWD2
    pvm: PvM
    afk: AFK
    ed1: ED1
    ed2: ED2
    ed3: ED3
    dpm: DPM
    hm: HM
