files:
  includes:
    - getting-started/quick-start.txt
    - getting-started/bossing-path.txt
    - getting-started/revo-to-full-manual.txt
    - getting-started/interface-guide.txt
    - getting-started/learning-pvm.txt

    - invention-and-perks/**/*.txt
    - miscellaneous-information/**/*.txt

    - upgrading-info/upgrade-order/*.txt
    - upgrading-info/**/*.txt

    - dpm-advice/**/*.txt
    - afk/**/*.txt
    - basic-guides/**/*.txt
    - rs3-full-boss-guides/**/*.txt

    - slayer/overview-of-slayer.txt
    - slayer/block-prefer-list.txt
    - slayer/ultimate-slayer.txt
    - slayer/miscellaneous-slayer.txt
    - slayer/**/*.txt

    - osrs-guides/**/*.txt

  excludes:
    - archive/**/*.txt
    - commands/**/*.txt
    - get-involved/**/*.txt
    - editor-resources/**/*.txt
    - navigation/**/*.txt
    - osrs-commands/**/*.txt
    - miscellaneous-information/command-info.txt
    - afk/afk-overview.txt

#  uncategorized:
#    - '**/*.txt'

name_convert:
  category:
    invention-and-perks:
      alias: perks
      emoji: 689509250946695292
    miscellaneous-information:
      alias: miscellaneous
    osrs-guides:
      alias: osrs
    upgrading-info:
      alias: upgrades
    slayer:
      emoji: 797896049548066857
    rs3-full-boss-guides:
      alias: full boss guides

  # channel
  channel:

    val: None

  word:
    osrs: OSRS
    gwd: GWD
    pvm: PvM
    afk: AFK
    ed: ED
    Ed: ED  # using this for some reason
    botlg: BotLG
    fsoa: fSoA
    dpm: DPM